### ISSUE TITLE
Deploy Kueue cluster automatically

### ISSUE THREAD

**Issue by xaviertintin** [xaviertintin/Thesis#10]
Deploy Kueue cluster automatically during REANA deployment when the admin chooses to use Kueue in their Helm values file. Allow basic parametrisation of Kueue deployment by overriding Helm values and/or chart snippets.

**Comment by xaviertintin** [comment]
Regarding kueue-related configurations like the ones I see [here](https://github.com/xaviertintin/reana/commit/d5bfb59042d2b0aa96ecad843a7c23a9bc1dfc02) in the scripts directory, these should definitely be part of the REANA helm chart, and they should be created only when kueue is enabled in the settings. As an example, this is how we [conditionally create ingress classes in REANA](https://github.com/reanahub/reana/blob/8ce4a8de6a46d427ac134b22f69a295e878ffdd8/helm/reana/templates/ingress.yaml#L1).

**Comment by xaviertintin** [comment]
Done, changes are:
1. [Add kueue parameters into the REANA helm chart](https://github.com/xaviertintin/reana/blob/2caff3172830e33570143861dc100df87895a96c/helm/reana/values.yaml#L171-L181)
2. [Add kueue template to deploy kueue automatically](https://github.com/xaviertintin/reana/blob/master/helm/reana/templates/kueue.yaml)

## Test 

Successful kueue deployment in reana-dev with:

```
kind delete cluster --name kind
cd '/Users/alextintin/project/reana/src/reana'
pip install -e .    
cd ~/project/reana/src
reana-dev cluster-create -m /var/reana:/var/reana --mode=debug

VERSION=v0.6.2
kubectl apply --server-side -f https://github.com/kubernetes-sigs/kueue/releases/download/$VERSION/manifests.yaml
kubectl wait --for=condition=available deployment/kueue-controller-manager -n kueue-system --timeout=5m

reana-dev cluster-build --parallel 8 --exclude-components r-a-vomsproxy -b DEBUG=1
reana-dev cluster-deploy --admin-email john.doe@example.org --admin-password mysecretpassword --mode=debug
```

---

Successful workflow submission

Batch Job Submission with Kueue

![Image](https://github.com/xaviertintin/Thesis/assets/79267255/3423cfc2-104f-4d36-b5fb-42a3edc0b352)

Job Submission with Kueue

![Image](https://github.com/xaviertintin/Thesis/assets/79267255/07bc6a07-a33a-45a8-acc8-39c0b58401d6)

Workflow completion

![Image](https://github.com/xaviertintin/Thesis/assets/79267255/73967589-aa99-47a3-a4c2-fddb11743e7d)

**Comment by mdonadoni** [comment]
This also looks good, I just have some cosmetics comments, but they are easily reported/solved in a PR where I can comment each line separately.
